### ISSUE TITLE
give me wall weapons. 

### ISSUE THREAD

**Issue by mofu23** [hellomotolegacy/requiem#18]
i swear to god moto. if i have to come here to get some god damn wall weapons, i will lick your ass

**Comment by hellomotolegacy** [comment]
Calm down, Omar. Ask Casey/Derped_Crusader for the model, edit the FGD and change the frames to the new ones. Ask about which are which.

**Comment by DerpedCrusader** [comment]
Muthafucca I sent them too you on discord, the frames are all in chat. I literally cannot baby feed it to you anymore than I have.

Really not In the mood for this.

**Comment by mofu23** [comment]
How do I edit the fgd?

**Comment by hellomotolegacy** [comment]
@DerpedCrusader Don't send your hate towards me. I don't have Discord, my account is gone. I can NOT go back and get them.

@mofu23 Check the announcements channel in the Discord and there will be a link to the FGD, open it in a text editor, do a search for "weapon_wall", the rest is self explanatory.

**Comment by mofu23** [comment]
Got it.

**Comment by mofu23** [comment]
so....i fucked up the fgd

**Comment by hellomotolegacy** [comment]
How so?

**Comment by mofu23** [comment]
My Skype ID mofu232

**Comment by DerpedCrusader** [comment]
@hellomotolegacy  i was talking to mofu in my message, i sent him the mdl and the frames, and i talked to him on discord, no hate between anyone

**Comment by hellomotolegacy** [comment]
My apologies. Closing this topic.
