### ISSUE TITLE
Direct X9 Support

### ISSUE THREAD

**Issue by BCDeshiG** [hellomotolegacy/requiem#6]
DX9 support vanished. Please add it back along with Vulkan.
EDIT: May possibly be my end, gonna reinstall dx9 first.
EDIT2: My Dx9 works, tested with old requiem (not clean).

**Comment by BCDeshiG** [comment]
Temporary fix? (old version): https://github.com/hellomotolegacy/requiem-clean/tree/d40d9768cf9dd7a7b5d30256ffd4412b31111740

**Comment by hellomotolegacy** [comment]
> EDIT2: My Dx9 works, tested with old requiem (not clean).

I don't understand what you mean by this second edit, does DX9 work or does it not?

**Comment by BCDeshiG** [comment]
It doesn't last I checked.

**Comment by hellomotolegacy** [comment]
Almost certain this was intentional, since FTEQW is cross-platform and DirectX is exclusive to the Windows platform. Closing issue.
